name = "demiz-writer"
main = "src/index.js"
compatibility_date = "2026-08-14"

[vars]
GITHUB_REPOSITORY = "DemiZovo/DemiZ"
GITHUB_BRANCH = "main"
ALLOWED_GITHUB_USER_ID = "304166225"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
